(function(g){var window=this;var Kxa=function(a,b){return g.Sb(a,b)},I6=function(a){g.sm(a,"zx",g.xb());
return a},J6=function(a,b,c){g.xa(c)||(c=[String(c)]);
g.vm(a.g,b,c)},Lxa=function(a,b){var c=[];
g.ek(b,function(a){try{var b=g.PC.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.OC(b)&&c.push(a):c.push(a)},a);
return c},Mxa=function(a,b){var c=Lxa(a,b);
(0,g.C)(c,function(a){g.PC.prototype.remove.call(this,a)},a)},Nxa=function(){var a=g.iG;
Mxa(a,a.g.ae(!0))},Oxa=function(a,b,c,d){var e=new g.jm(null,void 0);
a&&g.km(e,a);b&&g.lm(e,b);c&&g.mm(e,c);d&&g.nm(e,d);return e},Pxa=function(a){g.wF[a]&&(a=g.wF[a],(0,g.C)(a,function(a){g.uF[a]&&delete g.uF[a]}),a.length=0)},Qxa=function(a){var b=g.tF();
if(b)if(b.clear(a),a)Pxa(a);else for(var c in g.wF)Pxa(c)},K6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.A=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.dm;this.g=this.o="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Rxa(this,a.capabilities||""),Sxa(this,a.experiments||""),this.o=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},Rxa=function(a,b){a.capabilities.clear();
(0,g.Gd)(b.split(","),g.Da(Kxa,Txa)).forEach(function(b){a.capabilities.add(b)})},Sxa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},L6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},M6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},Uxa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},Vxa=function(a){return new L6(a)},Wxa=function(a){return g.xa(a)?(0,g.J)(a,Vxa):[]},N6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},O6=function(a){return g.xa(a)?"["+(0,g.J)(a,N6).join(",")+"]":"null"},P6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},Xxa=function(a){return(0,g.J)(a,function(a){return{key:a.id,
name:a.name}})},Q6=function(a,b){return g.Ia(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},R6=function(a,b){return g.Ia(a,function(a){return M6(a,b)})},S6=function(){var a=g.lG("yt-remote-connected-devices")||[];
g.eb(a);return a},Yxa=function(a){if(g.Na(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.J)(a,function(a,b){return 0==b?a:a.substring(c.length)})},Zxa=function(a){g.kG("yt-remote-connected-devices",a,86400)},U6=function(){if(T6)return T6;
var a=g.lG("yt-remote-device-id");a||(a=P6(),g.kG("yt-remote-device-id",a,31536E3));for(var b=S6(),c=1,d=a;g.D(b,d);)c++,d=a+"#"+c;return T6=d},V6=function(){var a=S6(),b=U6();
g.D(a,b);g.qG()&&g.gb(a,b);a=Yxa(a);if(g.Na(a))try{g.oG.remove("remote_sid","/","youtube.com")}catch(c){}else try{g.pG("remote_sid",a.join(","),-1)}catch(c){}},$xa=function(){return g.lG("yt-remote-session-browser-channel")},aya=function(){return g.lG("yt-remote-local-screens")||[]},bya=function(){g.kG("yt-remote-lounge-token-expiration",!0,86400)},cya=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.J)(aya(),function(a){return a.loungeToken}),c=(0,g.J)(a,function(a){return a.loungeToken});
(0,g.Sl)(c,function(a){return!g.D(b,a)})&&bya();
g.kG("yt-remote-local-screens",a,31536E3)},dya=function(a,b){g.kG("yt-remote-session-browser-channel",a);
g.kG("yt-remote-session-screen-id",b);var c=S6(),d=U6();g.D(c,d)||c.push(d);Zxa(c);V6()},W6=function(a){a||(g.mG("yt-remote-session-screen-id"),g.mG("yt-remote-session-video-id"));
V6();a=S6();g.Sa(a,U6());Zxa(a)},eya=function(){if(!X6){var a=g.VC();
a&&(X6=new g.JC(a))}return X6?!!X6.get("yt-remote-use-staging-server"):!1},fya=function(){var a=window.document.createElement("a");
g.Vc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Cb(a)},gya=function(a,b){var c=g.yd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.Wc(c,g.Yd("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},hya=function(){var a=fya(),b=window.document.getElementById(a),c=b&&g.HE(b,"loaded");
c||b&&!c||(b=gya(a,function(){g.HE(b,"loaded")||(g.GE(b,"loaded","true"),g.AF(a),g.DD(g.Da(Qxa,a),0))}))},iya=function(){var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);
return a?(0,window.parseInt)(a[1],10):0},Y6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},jya=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},kya=function(a,b){var c=new window.XMLHttpRequest;
c.onreadystatechange=function(){4==c.readyState&&200==c.status&&b(!0)};
c.onerror=function(){b(!1)};
try{c.open("GET",a,!0),c.send()}catch(d){b(!1)}},b7=function(a){if(a>=lya.length)Z6();
else{var b=lya[a],c="chrome-extension://"+b+mya;0<=$6.indexOf(b)?kya(c,function(d){d?(window.chrome.cast=window.chrome.cast||{},window.chrome.cast.extensionId=b,a7(c,Z6)):b7(a+1)}):a7(c,function(){b7(a+1)})}},a7=function(a,b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},c7=function(a){return 0<=window.navigator.userAgent.indexOf(a)},Z6=function(){var a=jya();
a&&a(!1,"No cast extension found")},oya=function(){if(nya){var a=2,b=jya(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;a7("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",Z6,c)}},pya=function(){if(c7("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){oya();a({command:"cast.sender.init"});return}}if(!window.chrome||c7("Edge"))Z6();else if(oya(),c7("Android")&&c7("Chrome/")&&window.navigator.presentation){a="";var b=iya();55<=b?a="55":50<=b&&(a="50");a7("//www.gstatic.com/eureka/clank"+a+mya,Z6)}else b7(0)},d7=function(a,b,c){g.M.call(this);
this.D=null!=c?(0,g.z)(a,c):a;this.xc=b;this.C=(0,g.z)(this.PH,this);this.g=!1;this.o=0;this.A=this.Ba=null;this.B=[]},e7=function(){},f7=function(a,b,c,d){this.g=a;
this.A=b;this.G=c;this.F=d||1;this.C=45E3;this.B=new g.zm(this);this.o=new g.ng;this.o.setInterval(250)},rya=function(a,b,c){a.rj=1;
a.oh=I6(b.clone());a.Li=c;a.D=!0;qya(a,null)},g7=function(a,b,c,d,e){a.rj=1;
a.oh=I6(b.clone());a.Li=null;a.D=c;e&&(a.sC=!1);qya(a,d)},qya=function(a,b){a.Wj=(0,g.H)();
h7(a);a.Ih=a.oh.clone();J6(a.Ih,"t",a.F);a.Vl=0;a.Qc=a.g.Tq(a.g.Pl()?b:null);0<a.Cr&&(a.Wo=new g.Ik((0,g.z)(a.zD,a,a.Qc),a.Cr));a.B.T(a.Qc,"readystatechange",a.KS);var c=a.li?g.$b(a.li):{};a.Li?(a.Dp="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Qc.send(a.Ih,a.Dp,a.Li,c)):(a.Dp="GET",a.sC&&!g.ud&&(c.Connection="close"),a.Qc.send(a.Ih,a.Dp,null,c));a.g.uf(1)},uya=function(a,b,c){for(var d=!0;!a.Vh&&a.Vl<c.length;){var e=sya(a,c);
if(e==i7){4==b&&(a.ph=4,j7(15),d=!1);break}else if(e==tya){a.ph=4;j7(16);d=!1;break}else k7(a,e)}4==b&&0==c.length&&(a.ph=1,j7(17),d=!1);a.yf=a.yf&&d;d||(l7(a),m7(a))},sya=function(a,b){var c=a.Vl,d=b.indexOf("\n",c);
if(-1==d)return i7;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return tya;d+=1;if(d+c>b.length)return i7;var e=b.substr(d,c);a.Vl=d+c;return e},wya=function(a,b){a.Wj=(0,g.H)();
h7(a);var c=b?window.location.hostname:"";a.Ih=a.oh.clone();g.sm(a.Ih,"DOMAIN",c);g.sm(a.Ih,"t",a.F);try{a.zf=new window.ActiveXObject("htmlfile")}catch(n){l7(a);a.ph=7;j7(22);m7(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in n7)k=n7[l];else if(l in vya)k=n7[l]=vya[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=n7[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.Xc(g.uc("b/12014412"),d);a.zf.open();a.zf.write(g.Pc(c));a.zf.close();a.zf.parentWindow.m=(0,g.z)(a.PR,a);a.zf.parentWindow.d=(0,g.z)(a.JB,a,!0);a.zf.parentWindow.rpcClose=(0,g.z)(a.JB,a,!1);c=a.zf.createElement("DIV");a.zf.parentWindow.document.body.appendChild(c);d=g.Gc(a.Ih.toString());d=g.ob(g.Dc(d));d=g.Xc(g.uc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.Pc(d);
a.g.uf(1)},h7=function(a){a.Zu=(0,g.H)()+a.C;
xya(a,a.C)},xya=function(a,b){if(null!=a.tk)throw Error("WatchDog timer not null");
a.tk=o7((0,g.z)(a.gS,a),b)},p7=function(a){a.tk&&(g.w.clearTimeout(a.tk),a.tk=null)},m7=function(a){a.g.Vx()||a.Vh||a.g.Lo(a)},l7=function(a){p7(a);
g.We(a.Wo);a.Wo=null;a.o.stop();g.Fm(a.B);if(a.Qc){var b=a.Qc;a.Qc=null;b.abort();b.dispose()}a.zf&&(a.zf=null)},k7=function(a,b){try{a.g.CB(a,b),a.g.uf(4)}catch(c){}},zya=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;yya(a,b,function(e){e?c(!0):g.w.setTimeout(function(){zya(a,b,c,d,f)},f)})}},yya=function(a,b,c){var d=new window.Image;
d.onload=function(){try{q7(d),c(!0)}catch(e){}};
d.onerror=function(){try{q7(d),c(!1)}catch(e){}};
d.onabort=function(){try{q7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{q7(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},q7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},Aya=function(a){this.g=a;
this.o=new e7},Bya=function(a){var b=r7(a.g,a.wk,"/mail/images/cleardot.gif");
I6(b);zya(b.toString(),5E3,(0,g.z)(a.YG,a),3,2E3);a.uf(1)},t7=function(a){var b=a.g.I;
if(null!=b)j7(5),b?(j7(11),s7(a.g,a,!1)):(j7(12),s7(a.g,a,!0));else if(a.re=new f7(a,void 0,void 0,void 0),a.re.li=a.zr,b=a.g,b=r7(b,b.Pl()?a.Wk:null,a.Br),j7(5),!g.sd||g.qc(10))J6(b,"TYPE","xmlhttp"),g7(a.re,b,!1,a.Wk,!1);else{J6(b,"TYPE","html");var c=a.re;a=!!a.Wk;c.rj=3;c.oh=I6(b.clone());wya(c,a)}},u7=function(a,b,c){this.g=1;
this.o=[];this.B=[];this.C=new e7;this.G=a||null;this.I=null!=b?b:null;this.D=c||!1},Cya=function(a,b){this.g=a;
this.map=b;this.context=null},Dya=function(a){g.Ye.call(this,"statevent",a)},Eya=function(a,b){g.Ye.call(this,"timingevent",a);
this.size=b},Fya=function(a){g.Ye.call(this,"serverreachability",a)},Iya=function(a){Gya(a);
if(3==a.g){var b=a.El++,c=a.Gn.clone();g.sm(c,"SID",a.A);g.sm(c,"RID",b);g.sm(c,"TYPE","terminate");v7(a,c);b=new f7(a,a.A,b,void 0);b.rj=2;b.oh=I6(c.clone());(new window.Image).src=b.oh;b.Wj=(0,g.H)();h7(b)}Hya(a)},Jya=function(a){a.wH(1,0);
a.Gn=r7(a,null,a.yr);w7(a)},Gya=function(a){a.eh&&(a.eh.abort(),a.eh=null);
a.uc&&(a.uc.cancel(),a.uc=null);a.xg&&(g.w.clearTimeout(a.xg),a.xg=null);x7(a);a.Qd&&(a.Qd.cancel(),a.Qd=null);a.gh&&(g.w.clearTimeout(a.gh),a.gh=null)},Kya=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.o.push(new Cya(a.RN++,b));2!=a.g&&3!=a.g||w7(a)},w7=function(a){a.Qd||a.gh||(a.gh=o7((0,g.z)(a.HB,a),0),a.jj=0)},Mya=function(a,b){if(1==a.g){if(!b){a.El=Math.floor(1E5*Math.random());
var c=a.El++,d=new f7(a,"",c,void 0);d.li=null;var e=y7(a),f=a.Gn.clone();g.sm(f,"RID",c);g.sm(f,"CVER","1");v7(a,f);rya(d,f,e);a.Qd=d;a.g=2}}else 3==a.g&&(b?Lya(a,b):0==a.o.length||a.Qd||Lya(a))},Lya=function(a,b){if(b)if(6<a.Xh){a.o=a.B.concat(a.o);
a.B.length=0;var c=a.El-1;var d=y7(a)}else c=b.G,d=b.Li;else c=a.El++,d=y7(a);var e=a.Gn.clone();g.sm(e,"SID",a.A);g.sm(e,"RID",c);g.sm(e,"AID",a.Ej);v7(a,e);c=new f7(a,a.A,c,a.jj+1);c.li=null;c.setTimeout(Math.round(1E4)+Math.round(1E4*Math.random()));a.Qd=c;rya(c,e,d)},v7=function(a,b){if(a.sd){var c=a.sd.Cx();
c&&g.Jb(c,function(a,c){g.sm(b,c,a)})}},y7=function(a){var b=Math.min(a.o.length,1E3),c=["count="+b];
if(6<a.Xh&&0<b){var d=a.o[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.o[e].g,k=a.o[e].map;f=6>=a.Xh?e:f-d;try{g.Jb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.B=a.B.concat(a.o.splice(0,b));
return c.join("&")},Nya=function(a){a.uc||a.xg||(a.F=1,a.xg=o7((0,g.z)(a.GB,a),0),a.aj=0)},z7=function(a){if(a.uc||a.xg||3<=a.aj)return!1;
a.F++;a.xg=o7((0,g.z)(a.GB,a),Oya(a,a.aj));a.aj++;return!0},s7=function(a,b,c){a.Cp=c;
a.jf=b.Eg;a.D||Jya(a)},x7=function(a){null!=a.Zh&&(g.w.clearTimeout(a.Zh),a.Zh=null)},Oya=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},A7=function(a,b){if(2==b||9==b){var c=null;
a.sd&&(c=null);var d=(0,g.z)(a.FT,a);c||(c=new g.jm("//www.google.com/images/cleardot.gif"),I6(c));yya(c.toString(),1E4,d)}else j7(2);Pya(a,b)},Pya=function(a,b){a.g=0;
a.sd&&a.sd.zw(b);Hya(a);Gya(a)},Hya=function(a){a.g=0;
a.jf=-1;if(a.sd)if(0==a.B.length&&0==a.o.length)a.sd.Iq();else{g.Va(a.B);var b=g.Va(a.o);a.B.length=0;a.o.length=0;a.sd.Iq(b)}},r7=function(a,b,c){var d=g.tm(c);
if(""!=d.o)b&&g.lm(d,b+"."+d.o),g.mm(d,d.C);else{var e=window.location;d=Oxa(e.protocol,b?b+"."+e.hostname:e.hostname,e.port,c)}a.Jk&&g.Jb(a.Jk,function(a,b){g.sm(d,b,a)});
g.sm(d,"VER",a.Xh);v7(a,d);return d},o7=function(a,b){if(!g.za(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},j7=function(a){B7.dispatchEvent(new Dya(B7,a))},Qya=function(){},Rya=function(a,b){this.action=a;
this.params=b||{}},D7=function(a,b){g.M.call(this);
this.g=new g.Nt(this.A,0,this);g.N(this,this.g);this.o=this.xc=0;if(g.za(a))b&&(a=(0,g.z)(a,b));else if(a&&g.za(a.handleEvent))a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a;C7(this)},C7=function(a){a.g.stop();
a.xc=5E3+2E4*Math.random()},E7=function(a,b,c){this.L=a;
this.D=b;this.A=new g.IC;this.o=new D7(this.mU,this);this.g=this.bb=null;this.J=!1;this.C=null;this.I="";this.G=this.B=0;this.F=[];this.N=c||!1},Sya=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Cp,sessionId:a.g.A,arrayId:a.g.Ej}},Tya=function(a,b){a.G=b||0;
a.o.stop();a.g&&(3==a.g.g&&Mya(a.g),Iya(a.g));a.G=0},F7=function(a){return!!a.g&&3==a.g.g},Uya=function(a,b){(a.D.loungeIdToken=b)||a.o.stop()},G7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.Dg(a)||"";b&&(this.port=":"+b);this.domain=g.Cg(a)||"";a=g.Hb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Bb(a,"10.0")&&(this.o=!1))},H7=function(a,b){var c=a.g;
if(g.t(void 0)?0:a.o)c="https://"+a.domain+a.port+a.g;return g.Mg(c+b,{})},I7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,Lb:g.Da(a.B,d,!0),onError:g.Da(a.A,e),wd:g.Da(a.C,e)};c&&(a.Pb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.TD(b,a)},Yya=function(){var a=Vya;
Wya();J7.push(a);Xya(J7)},K7=function(a,b){Wya();
var c=J7,d=Zya(a,String(b));g.Na(c)?$ya(d):(Xya(c),(0,g.C)(c,function(a){a(d)}))},Wya=function(){J7||(J7=g.x("yt.mdx.remote.debug.handlers_")||[],g.ua("yt.mdx.remote.debug.handlers_",J7,void 0))},$ya=function(a){var b=(L7+1)%50;
L7=b;M7[b]=a;N7||(N7=49==b)},Xya=function(a){var b=M7;
if(b[0]){var c=L7,d=N7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.C)(a,function(a){a(e)})}while(d!=c);
M7=Array(50);L7=-1;N7=!1}},Zya=function(a,b){var c=((0,g.H)()-aza)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},O7=function(a){g.lF.call(this);
this.F=a;this.g=[]},bza=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},cza=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Gd)(a.g,function(a){return!!Q6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=bza(a,b[d])||c;return c},dza=function(a,b){var c=a.g.length;
a.g=(0,g.Gd)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},P7=function(a,b,c,d){g.lF.call(this);
this.D=a;this.C=b;this.A=c;this.B=d;this.o=0;this.g=null;this.Ba=window.NaN},R7=function(a){O7.call(this,"LocalScreenService");
this.A=a;this.o=window.NaN;Q7(this);this.info("Initializing with "+O6(this.g))},eza=function(a){if(a.g.length){var b=(0,g.J)(a.g,function(a){return a.id}),c=H7(a.A,"/pairing/get_lounge_token_batch");
I7(a.A,c,{screen_ids:b.join(",")},(0,g.z)(a.bI,a),(0,g.z)(a.aI,a))}},Q7=function(a){var b=Wxa(aya());
b=(0,g.Gd)(b,function(a){return!a.uuid});
return cza(a,b)},S7=function(a,b){cya((0,g.J)(a.g,Uxa));
b&&bya()},U7=function(a,b){g.lF.call(this);
this.D=b;var c=g.lG("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.D(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.D(c,l)}this.g=d;this.C=a;this.A=this.B=window.NaN;this.o=null;T7("Initialized with "+g.ug(this.g))},fza=function(a,b,c){var d=H7(a.C,"/pairing/get_screen_availability");
I7(a.C,d,{lounge_token:b.token},(0,g.z)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},V7=function(a,b){a:if(g.Nb(b)!=g.Nb(a.g))var c=!1;
else{c=g.Pb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(T7("Updated online screens: "+g.ug(a.g)),a.g=b,a.U("screenChange"));gza(a)},W7=function(a){(0,window.isNaN)(a.A)||g.FD(a.A);
a.A=g.DD((0,g.z)(a.ju,a),0<a.B&&a.B<(0,g.H)()?2E4:1E4)},T7=function(a){K7("OnlineScreenService",a)},hza=function(a){var b={};
(0,g.C)(a.D(),function(a){a.token?b[a.token]=a.id:this.dc("Requesting availability of screen w/o lounge token.")});
return b},gza=function(a){a=g.Pb(g.Kb(a.g,function(a){return a}));
g.eb(a);a.length?g.kG("yt-remote-online-screen-ids",a.join(","),60):g.mG("yt-remote-online-screen-ids")},X7=function(a){O7.call(this,"ScreenService");
this.D=a;this.o=this.A=null;this.B=[];this.C={};iza(this)},kza=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.C[b]);var k=a.ie();if(k=(c?R6(k,c):null)||R6(k,b)){k.uuid=b;var l=Y7(a,k);fza(a.o,l,function(a){e(a?l:null)})}else c?jza(a,c,(0,g.z)(function(a){var f=Y7(this,new L6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));fza(this.o,f,function(a){e(a?f:null)})},a),f):e(null)},lza=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},jza=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Pb:{screen_ids:b},method:"POST",context:a,Lb:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.TD(H7(a.D,"/pairing/get_lounge_token_batch"),e)},mza=function(a){a.g=a.A.ie();
var b=a.C,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+O6(a.g))},iza=function(a){Z7(a);
a.A=new R7(a.D);a.A.subscribe("screenChange",(0,g.z)(a.nI,a));mza(a);a.B=Wxa(g.lG("yt-remote-automatic-screen-cache")||[]);Z7(a);a.info("Initializing automatic screens: "+O6(a.B));a.o=new U7(a.D,(0,g.z)(a.ie,a,!0));a.o.subscribe("screenChange",(0,g.z)(function(){this.U("onlineScreenChange")},a))},Y7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=R6(a.B,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.B.push(b),g.kG("yt-remote-automatic-screen-cache",(0,g.J)(a.B,Uxa)));Z7(a);a.C[b.uuid]=b.id;g.kG("yt-remote-device-id-map",a.C,31536E3);return b},Z7=function(a){a.C=g.lG("yt-remote-device-id-map")||{}},$7=function(a,b,c){g.lF.call(this);
this.N=c;this.I=a;this.o=b;this.A=null},a8=function(a,b){K7(a.N,b)},b8=function(a,b){$7.call(this,a,b,"CastSession");
this.g=null;this.B=0;this.D=(0,g.z)(this.sU,this);this.C=(0,g.z)(this.qS,this);this.B=g.DD((0,g.z)(function(){nza(this,null)},this),12E4)},oza=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.ug(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.y,(0,g.z)(function(){a8(this,"Failed to send message: getMdxSessionStatus.")},a)):a8(a,"Sending yt message without session: "+g.ug(b))},nza=function(a,b){g.FD(a.B);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.A||a.A.id!=b){var c=(0,g.z)(a.Mo,a),d=(0,g.z)(a.pe,a);a.Ox(b,c,d,5)}}else a.pe(Error("Waiting for session status timed out."))},c8=function(a,b,c){$7.call(this,a,b,"DialSession");
this.B=this.G=null;this.J="";this.O=c;this.C=null;this.F=g.y;this.D=window.NaN;this.L=(0,g.z)(this.vU,this);this.g=g.y},pza=function(a){a.g=a.I.FD(a.J,a.o.label,a.o.friendlyName,(0,g.z)(function(a){this.g=g.y;
this.Mo(a)},a),(0,g.z)(function(a){this.g=g.y;
this.pe(a)},a))},qza=function(a){var b={};
b.pairingCode=a.J;b.theme=a.O;if(a.C){var c=a.C.currentTime||0;b.v=a.C.videoId;b.t=c}eya()&&(b.env_useStageMdx=1);return g.Kg(b)},d8=function(a,b){$7.call(this,a,b,"ManualSession");
this.g=g.DD((0,g.z)(this.Fj,this,null),150)},e8=function(a,b,c,d){g.lF.call(this);
this.o=a;this.F=b||"233637DE";this.D=c||"cl";this.G=d||!1;this.g=null;this.C=!1;this.A=[];this.B=(0,g.z)(this.WQ,this)},rza=function(a,b){return b?g.Ia(a.A,function(a){return M6(b,a.label)},a):null},f8=function(a){K7("Controller",a)},Vya=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},g8=function(a){return a.C||!!a.A.length||!!a.g},h8=function(a,b,c){b!=a.g&&(g.We(a.g),(a.g=b)?(c?a.U("yt-remote-cast2-receiver-resumed",b.o):a.U("yt-remote-cast2-receiver-selected",
b.o),b.subscribe("sessionScreen",(0,g.z)(a.EB,a,b)),b.A?a.U("yt-remote-cast2-session-change",b.A):c&&a.g.Fj(null)):a.U("yt-remote-cast2-session-change",null))},sza=function(a){var b=a.o.ED(),c=a.g&&a.g.o;
a=(0,g.J)(b,function(a){c&&M6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=rza(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},xza=function(a,b,c,d,e,f,k){tza()?uza(b,e,f,k)&&(j8(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?vza(a,c):(window.__onGCastApiAvailable=function(b,d){b?vza(a,c):(k8("Failed to load cast API: "+d),l8(!1),j8(!1),g.mG("yt-remote-cast-available"),g.mG("yt-remote-cast-receiver"),wza(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):hya():pya())):i8("Cannot initialize because not running Chrome")},wza=function(){i8("dispose");
var a=m8();a&&a.dispose();g.ua("yt.mdx.remote.cloudview.instance_",null,void 0);yza(!1);g.yF(n8);n8.length=0},o8=function(){return!!g.lG("yt-remote-cast-installed")},zza=function(){var a=g.lG("yt-remote-cast-receiver");
return a?a.friendlyName:null},Aza=function(){i8("clearCurrentReceiver");
g.mG("yt-remote-cast-receiver")},Bza=function(){return o8()?m8()?m8().getCastSession():(k8("getCastSelector: Cast is not initialized."),null):(k8("getCastSelector: Cast API is not installed!"),null)},q8=function(){o8()?m8()?p8()?(i8("Requesting cast selector."),m8().requestSession()):(i8("Wait for cast API to be ready to request the session."),n8.push(g.xF("yt-remote-cast2-api-ready",q8))):k8("requestCastSelector: Cast is not initialized."):k8("requestCastSelector: Cast API is not installed!")},r8=
function(a,b){p8()?m8().setConnectedScreenStatus(a,b):k8("setConnectedScreenStatus called before ready.")},tza=function(){var a=0<=g.Hb.search(/ (CrMo|Chrome|CriOS)\//);
return g.aJ||a},Cza=function(a,b){m8().init(a,b)},uza=function(a,b,c,d){var e=!1;
m8()||(a=new e8(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.kG("yt-remote-cast-available",a);g.BF("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){i8("onReceiverSelected: "+a.friendlyName);
g.kG("yt-remote-cast-receiver",a);g.BF("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){i8("onReceiverResumed: "+a.friendlyName);
g.kG("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){i8("onSessionChange: "+N6(a));
a||g.mG("yt-remote-cast-receiver");g.BF("yt-remote-cast2-session-change",a)}),g.ua("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
i8("cloudview.createSingleton_: "+e);return e},m8=function(){return g.x("yt.mdx.remote.cloudview.instance_")},vza=function(a,b){l8(!0);
j8(!1);Cza(a,function(a){a?(yza(!0),g.AF("yt-remote-cast2-api-ready")):(k8("Failed to initialize cast API."),l8(!1),g.mG("yt-remote-cast-available"),g.mG("yt-remote-cast-receiver"),wza());b(a)})},i8=function(a){K7("cloudview",a)},k8=function(a){K7("cloudview",a)},l8=function(a){i8("setCastInstalled_ "+a);
g.kG("yt-remote-cast-installed",a)},p8=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},yza=function(a){i8("setApiReady_ "+a);
g.ua("yt.mdx.remote.cloudview.apiReady_",a,void 0)},j8=function(a){g.ua("yt.mdx.remote.cloudview.initializing_",a,void 0)},s8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.o=null;this.hasNext=this.Of=!1;this.J=this.I=this.A=this.C=0;this.B=window.NaN;this.D=!1;this.reset(a)},t8=function(a){a.audioTrackId=null;
a.o=null;a.g=-1;a.Of=!1;a.hasNext=!1;a.G=0;a.F=(0,g.H)();a.C=0;a.A=0;a.I=0;a.J=0;a.B=window.NaN;a.D=!1},u8=function(a){return a.ob()?((0,g.H)()-a.F)/1E3:0},v8=function(a,b){a.G=b;
a.F=(0,g.H)()},w8=function(a){switch(a.g){case 1:case 1081:return((0,g.H)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},x8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&t8(a)},y8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.ac(a.o);b.hasPrevious=a.Of;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.C;b.seekableEnd=a.A;b.duration=a.I;b.loadedTime=a.J;b.liveIngestionTime=a.B;return b},A8=function(a,b){g.lF.call(this);
this.g=0;this.B=a;this.D=[];this.C=new g.ZB;this.A=this.o=null;this.I=(0,g.z)(this.AO,this);this.F=(0,g.z)(this.Gl,this);this.G=(0,g.z)(this.zO,this);this.J=(0,g.z)(this.NO,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.fv,this),Dza(this))):c=3;0!=c&&(b?this.fv(c):g.DD((0,g.z)(function(){this.fv(c)},this),0));
var d=Bza();d&&z8(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},B8=function(a){return new s8(a.B.getPlayerContextData())},Dza=function(a){(0,g.C)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.Da(this.SQ,a),this))},a)},Eza=function(a){(0,g.C)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},C8=function(a,b){50>a.C.Mc()&&g.aC(a.C,b)},E8=function(a,b,c){var d=B8(a);
v8(d,c);-1E3!=d.g&&(d.g=b);D8(a,d)},F8=function(a,b,c){a.B.sendMessage(b,c)},D8=function(a,b){Eza(a);
a.B.setPlayerContextData(y8(b));Dza(a)},z8=function(a,b){a.A&&(a.A.removeUpdateListener(a.I),a.A.removeMediaListener(a.F),a.Gl(null));
a.A=b;a.A&&(K7("CP","Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.I),a.A.addMediaListener(a.F),a.A.media.length&&a.Gl(a.A.media[0]))},Fza=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=B8(a);b.contentId!=d.videoId&&K7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;v8(d,a.o.getEstimatedTime());D8(a,d)}else K7("CP","No cast media video. Ignoring state update.")},G8=function(a,b,c){return(0,g.z)(function(a){this.dc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.dc("Retrying "+b+" using MDx browser channel."),F8(this,b,c))},a)},H8=function(a,b,c){g.lF.call(this);
this.C=window.NaN;this.O=!1;this.J=this.I=this.L=this.N=window.NaN;this.R=[];this.B=this.F=this.A=this.fb=this.g=null;this.na=a;this.R.push(g.WE(window,"beforeunload",(0,g.z)(this.SH,this)));this.o=[];this.fb=new s8;this.aa=b.id;this.g=Gza(this,c);this.g.subscribe("handlerOpened",this.EO,this);this.g.subscribe("handlerClosed",this.BO,this);this.g.subscribe("handlerError",this.CO,this);this.g.subscribe("handlerMessage",this.DO,this);Uya(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.fb.videoId;g.qG()&&g.kG("yt-remote-session-video-id",a)},this)},I8=function(a){K7("conn",a)},Gza=function(a,b){return new E7(H7(a.na,"/bc"),b)},J8=function(a,b){a.U("proxyStateChange",b)},Hza=function(a){a.C=g.DD((0,g.z)(function(){I8("Connecting timeout");
this.D(1)},a),2E4)},K8=function(a){g.FD(a.C);
a.C=window.NaN},L8=function(a){g.FD(a.N);
a.N=window.NaN},Iza=function(a){M8(a);
a.L=g.DD((0,g.z)(function(){N8(this,"getNowPlaying")},a),2E4)},M8=function(a){g.FD(a.L);
a.L=window.NaN},Kza=function(a,b){b&&(K8(a),L8(a));
b==(F7(a.g)&&(0,window.isNaN)(a.C))?b&&(J8(a,1),N8(a,"getSubtitlesTrack")):b?(a.X()&&a.fb.reset(),J8(a,1),N8(a,"getNowPlaying"),Jza(a)):a.D(1)},Lza=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.fb.videoId&&(g.Vb(b.params)?a.fb.o=null:a.fb.o=b.params,a.U("remotePlayerChange"))},Mza=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.fb.listId=b.params.listId||a.fb.listId;x8(a.fb,c,d);a.U("remoteQueueChange")},Oza=function(a,b){b.params=b.params||{};
Mza(a,b);Nza(a,b);a.U("autoplayDismissed")},Nza=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
v8(a.fb,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.fb.g&&(c=-1E3);a.fb.g=c;c=Number(b.params.loadedTime);a.fb.J=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.fb.I=(0,window.isNaN)(c)?0:c;c=a.fb;var d=Number(b.params.liveIngestionTime);c.B=d;c.D=(0,window.isNaN)(d)?!1:!0;c=a.fb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=(0,window.isNaN)(d)?0:d;c.A=(0,window.isNaN)(e)?0:e;1==a.fb.g?Iza(a):M8(a);
a.U("remotePlayerChange")},Pza=function(a,b){if(-1E3!=a.fb.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.fb.g=c;c=(0,window.parseInt)(b.params.currentTime,10);v8(a.fb,(0,window.isNaN)(c)?0:c);a.U("remotePlayerChange")}},Qza=function(a,b){var c="true"==b.params.muted;
a.fb.volume=(0,window.parseInt)(b.params.volume,10);a.fb.muted=c;a.U("remotePlayerChange")},Rza=function(a,b){a.F=b.params.videoId;
a.U("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},Sza=function(a,b){var c="true"==b.params.hasNext;
a.fb.Of="true"==b.params.hasPrevious;a.fb.hasNext=c;a.U("previousNextChange")},Jza=function(a){g.FD(a.J);
a.J=g.DD((0,g.z)(a.D,a,1),864E5)},N8=function(a,b,c){c?I8("Sending: action="+b+", params="+g.ug(c)):I8("Sending: action="+b);
a.g.sendMessage(b,c)},O8=function(a){O7.call(this,"ScreenServiceProxy");
this.gd=a;this.o=[];this.o.push(this.gd.$_s("screenChange",(0,g.z)(this.qU,this)));this.o.push(this.gd.$_s("onlineScreenChange",(0,g.z)(this.yQ,this)))},Xza=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.xD("MDX_CONFIG")||b;g.iG&&Nxa();V6();P8||(P8=new G7(b?b.loungeApiHost:void 0),eya()&&(P8.g="/api/loungedev"));Q8||(Q8=g.x("yt.mdx.remote.deferredProxies_")||[],g.ua("yt.mdx.remote.deferredProxies_",Q8,void 0));Tza();var c=R8();if(!c){var d=new X7(P8);g.ua("yt.mdx.remote.screenService_",d,void 0);c=R8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);xza(a,d,function(a){a?S8()&&r8(S8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.BF("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.ua("yt.mdx.remote.initialized_",!0,void 0),T8("Initializing: "+g.ug(b)),U8.push(g.xF("yt-remote-cast2-availability-change",function(){g.BF("yt-remote-receiver-availability-change")})),U8.push(g.xF("yt-remote-cast2-receiver-selected",function(){V8(null);
g.BF("yt-remote-auto-connect","cast-selector-receiver")})),U8.push(g.xF("yt-remote-cast2-receiver-resumed",function(){g.BF("yt-remote-receiver-resumed","cast-selector-receiver")})),U8.push(g.xF("yt-remote-cast2-session-change",Uza)),U8.push(g.xF("yt-remote-connection-change",function(a){a?r8(S8(),"YouTube TV"):W8()||(r8(null,null),Aza())})),a=X8(),b.isAuto&&(a.id+="#dial"),g.mE("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),T8(" -- with channel params: "+
g.ug(a)),Vza(a),c.start(),S8()||Wza())},Zza=function(){var a=Yza();
o8()&&g.lG("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},Yza=function(){var a=R8().gd.$_gos();
var b=Y8();b&&Z8()&&(Q6(a,b)||a.push(b));return Xxa(a)},$8=function(){var a=$za();
!a&&o8()&&zza()&&(a={key:"cast-selector-receiver",name:zza()});return a},$za=function(){var a=Yza(),b=Y8();
b||(b=W8());return g.Ia(a,function(a){return b&&M6(b,a.key)?!0:!1})},Y8=function(){var a=S8();
if(!a)return null;var b=R8().ie();return R6(b,a)},Uza=function(a){T8("remote.onCastSessionChange_: "+N6(a));
if(a){var b=Y8();b&&b.id==a.id?r8(b.id,"YouTube TV"):(b&&a9(),b9(a,1))}else Z8()&&a9()},a9=function(){p8()?m8().stopSession():k8("stopSession called before API ready.");
var a=Z8();a&&(a.disconnect(1),c9(null))},d9=function(){var a=Z8();
return!!a&&3!=a.getProxyState()},T8=function(a){K7("remote",a)},R8=function(){if(!e9){var a=g.x("yt.mdx.remote.screenService_");
e9=a?new O8(a):null}return e9},S8=function(){return g.x("yt.mdx.remote.currentScreenId_")},aAa=function(a){g.ua("yt.mdx.remote.currentScreenId_",a,void 0)},bAa=function(){return g.x("yt.mdx.remote.connectData_")},V8=function(a){g.ua("yt.mdx.remote.connectData_",a,void 0)},Z8=function(){return g.x("yt.mdx.remote.connection_")},c9=function(a){var b=Z8();
V8(null);a||aAa("");g.ua("yt.mdx.remote.connection_",a,void 0);Q8&&((0,g.C)(Q8,function(b){b(a)}),Q8.length=0);
b&&!a?g.BF("yt-remote-connection-change",!1):!b&&a&&g.BF("yt-remote-connection-change",!0)},W8=function(){var a=g.qG();
if(!a)return null;var b=R8().ie();return R6(b,a)},b9=function(a,b){Y8()&&Y8();
aAa(a.id);var c=new H8(P8,a,X8());c.connect(b,bAa());c.subscribe("beforeDisconnect",function(a){g.BF("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){Z8()&&c9(null)});
c9(c)},Wza=function(){var a=W8();
a?(T8("Resume connection to: "+N6(a)),b9(a,0)):(W6(),Aza(),T8("Skipping connecting because no session screen found."))},Tza=function(){var a=X8();
if(g.Vb(a)){a=U6();var b=g.lG("yt-remote-session-name")||"",c=g.lG("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.ua("yt.mdx.remote.channelParams_",a,void 0)}},X8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},Vza=function(a){a?(g.kG("yt-remote-session-app",a.app),g.kG("yt-remote-session-name",a.name)):(g.mG("yt-remote-session-app"),g.mG("yt-remote-session-name"));
g.ua("yt.mdx.remote.channelParams_",a,void 0)},f9=function(a,b,c){g.M.call(this);
this.G=a;this.o=b;this.A=new g.iF(this);g.N(this,this.A);this.A.P(b,"onCaptionsTrackListChanged",this.RP);this.A.P(b,"captionschanged",this.yO);this.A.P(b,"captionssettingschanged",this.VC);this.A.P(b,"videoplayerreset",this.No);this.A.P(b,"mdxautoplaycancel",this.XG);this.R=this.A.P(b,"onVolumeChange",this.oB);this.F=!1;this.g=c;c.subscribe("proxyStateChange",this.BB,this);c.subscribe("remotePlayerChange",this.Il,this);c.subscribe("remoteQueueChange",this.No,this);c.subscribe("autoplayUpNext",this.aB,
this);c.subscribe("previousNextChange",this.yB,this);c.subscribe("nowAutoplaying",this.qB,this);c.subscribe("autoplayDismissed",this.ZA,this);this.suggestion=null;this.I=new g.eO(64);this.B=new g.Nt(this.RC,500,this);g.N(this,this.B);this.C=new g.Nt(this.SC,1E3,this);g.N(this,this.C);this.L=new d7(this.QT,0,this);g.N(this,this.L);this.D={};this.N=new g.Nt(this.tD,1E3,this);g.N(this,this.N);this.J=new g.Ik(this.kL,1E3,this);g.N(this,this.J);this.O=g.y;this.VC();this.No();this.Il()},g9=function(a,b){var c=
a.G,d=a.o.fa().lengthSeconds;
c.I=b||0;c.g.U("progresssync",b,d)},cAa=function(a){g9(a,0);
a.B.stop();h9(a,new g.eO(64))},j9=function(a,b){if(i9(a)&&!a.F){var c=null;
b&&(c={style:a.o.Di()},g.cc(c,b));a.g.JC(a.o.fa(1).videoId,c);a.D=B8(a.g).o}},k9=function(a,b){var c=a.o.ag();
if(c){var d=c.fe();var e=c.listId.toString()}var f=a.o.fa(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;f=f.Bj;var m=B8(c),n=e||m.listId;l=l||0;var q={videoId:k,currentIndex:l};x8(m,k,l);g.t(b)&&(v8(m,b),q.currentTime=b);g.t(n)&&(q.listId=n);null!=d&&(q.playerParams=d);null!=f&&(q.clickTrackingParams=f);F8(c,"setPlaylist",q);e||D8(c,m);h9(a,new g.eO(1))},dAa=function(a,b){if(b){var c=a.o.Bc("captions","tracklist",{My:1});
c&&c.length?(a.o.Id("captions","track",b),a.F=!1):(a.o.xl("captions"),a.F=!0)}else a.o.Id("captions","track",{})},i9=function(a){return B8(a.g).videoId==a.o.fa(1).videoId},h9=function(a,b){a.C.stop();
var c=a.I;if(!g.lO(c,b)){var d=g.V(b,2);d!=g.V(a.I,2)&&g.WT(a.o,d);a.I=b;eAa(a.G,c,b)}},l9=function(a){g.X.call(this,{H:"div",
M:"ytp-remote",K:[{H:"div",M:"ytp-remote-display-status",K:[{H:"div",M:"ytp-remote-display-status-icon",K:[g.TU()]},{H:"div",M:"ytp-remote-display-status-text",K:["{{statustext}}"]}]}]});this.o=new g.pV(this,250);g.N(this,this.o);this.A=a;this.P(a,"presentingplayerstatechange",this.B);fAa(this,g.TT(a))},fAa=function(a,b){if(3==a.A.Sa()){var c={RECEIVER_NAME:a.A.Bc("remote","currentReceiver").name};
c=g.V(b,128)?g.U("YTP_MDX_STATUS_ERROR_2",c):b.ob()||g.V(b,4)?g.U("YTP_MDX_STATUS_PLAYING_2",c):g.U("YTP_MDX_STATUS_CONNECTED_2",c);a.updateValue("statustext",c);a.o.show()}else a.o.hide()},m9=function(a,b){g.K_.call(this,g.U("YTP_MDX_TITLE"),0,a,b);
this.o=a;this.G={};this.P(a,"onMdxReceiversChange",this.J);this.P(a,"presentingplayerstatechange",this.J);this.J()},n9=function(a){g.tU.call(this,a);
this.A={key:P6(),name:g.U("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.J=this.o=null;this.G=[this.A];this.B=this.A;this.F=new g.eO(64);this.I=0;if(!g.NL(g.W(this.g))){a=this.g;var b=g.MT(a).I;b&&(b=b.A&&b.A.g)&&(b=new m9(a,b),g.N(this,b));b=new l9(a);g.N(this,b);g.nU(a,b.element,4)}},eAa=function(a,b,c){a.F=c;
a.g.U("presentingplayerstatechange",new g.rO(c,b))},o9=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)a9();
else{a.B=b;var c=a.g.getPlaylistId();var d=a.g.fa(1),e=d.videoId;if(c||e){var f=a.g.ag();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.kc(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.Bj,index:Math.max(a.g.Tz(),0),currentTime:0==f?void 0:f}}else c=null;T8("Connecting to: "+g.ug(b));"cast-selector-receiver"==b.key?(V8(c||null),p8()?m8().setLaunchParams(c||null):k8("setLaunchParams called before ready.")):!c&&
d9()&&S8()==b.key?g.BF("yt-remote-connection-change",!0):(a9(),V8(c||null),c=R8().ie(),(c=R6(c,b.key))&&b9(c,1))}},vya={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},n7={"'":"\\'"},gAa={},Txa={ZV:"atp",v0:"ska",L_:"que",a_:"mus",r0:"sus"};
K6.prototype.qn=function(){var a=new K6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.A=this.A;a.o=this.o;a.g=this.g};
var X6,T6="",mya=Y6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",nya=Y6("loadCastFramework")||Y6("loadCastApplicationFramework"),$6=["boadgeojelhgndaghljhdicfkmllpafd","dliochdbjfkdbacpmhlcpmleaejidimm","enhhojjnijigcajfphajepfemndkmdlo","fmfcbgogabcbclcofgocippekhfcmgfj"],hAa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","fjhoaacokmgbjemoflkofnenfaiekifl"],lya=50<=iya()?hAa.concat($6):$6.concat(hAa);g.A(d7,g.M);g.h=d7.prototype;g.h.OH=function(a){this.B=arguments;this.g=!1;this.Ba?this.A=(0,g.H)()+this.xc:this.Ba=g.og(this.C,this.xc)};
g.h.stop=function(){this.Ba&&(g.pg(this.Ba),this.Ba=null);this.A=null;this.g=!1;this.B=[]};
g.h.pause=function(){++this.o};
g.h.resume=function(){this.o&&(--this.o,!this.o&&this.g&&(this.g=!1,this.D.apply(null,this.B)))};
g.h.W=function(){this.stop();d7.Y.W.call(this)};
g.h.PH=function(){this.A?(this.Ba=g.og(this.C,this.A-(0,g.H)()),this.A=null):(this.Ba=null,this.o?this.g=!0:(this.g=!1,this.D.apply(null,this.B)))};e7.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
e7.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=f7.prototype;g.h.li=null;g.h.yf=!1;g.h.tk=null;g.h.Zu=null;g.h.Wj=null;g.h.rj=null;g.h.oh=null;g.h.Ih=null;g.h.Li=null;g.h.Qc=null;g.h.Vl=0;g.h.zf=null;g.h.Dp=null;g.h.ph=null;g.h.Xk=-1;g.h.sC=!0;g.h.Vh=!1;g.h.Cr=0;g.h.Wo=null;var tya={},i7={};g.h=f7.prototype;g.h.setTimeout=function(a){this.C=a};
g.h.KS=function(a){a=a.target;var b=this.Wo;b&&3==g.fx(a)?b.pj():this.zD(a)};
g.h.zD=function(a){try{if(a==this.Qc)a:{var b=g.fx(this.Qc),c=this.Qc.o,d=this.Qc.getStatus();if(g.sd&&!g.qc(10)||g.ud&&!g.pc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.$e&&!g.jx(this.Qc))break a;this.Vh||4!=b||7==c||(8==c||0>=d?this.g.uf(3):this.g.uf(2));p7(this);var e=this.Qc.getStatus();this.Xk=e;var f=g.jx(this.Qc);(this.yf=200==e)?(4==b&&l7(this),this.D?(uya(this,b,f),g.$e&&this.yf&&3==b&&(this.B.T(this.o,"tick",this.DS),this.o.start())):k7(this,f),this.yf&&!this.Vh&&(4==b?this.g.Lo(this):
(this.yf=!1,h7(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.ph=3,j7(13)):(this.ph=0,j7(14)),l7(this),m7(this))}}catch(k){this.Qc&&g.jx(this.Qc)}finally{}};
g.h.DS=function(){var a=g.fx(this.Qc),b=g.jx(this.Qc);this.Vl<b.length&&(p7(this),uya(this,a,b),this.yf&&4!=a&&h7(this))};
g.h.PR=function(a){o7((0,g.z)(this.OR,this,a),0)};
g.h.OR=function(a){this.Vh||(p7(this),k7(this,a),h7(this))};
g.h.JB=function(a){o7((0,g.z)(this.NR,this,a),0)};
g.h.NR=function(a){this.Vh||(l7(this),this.yf=a,this.g.Lo(this),this.g.uf(4))};
g.h.cancel=function(){this.Vh=!0;l7(this)};
g.h.gS=function(){this.tk=null;var a=(0,g.H)();0<=a-this.Zu?(2!=this.rj&&this.g.uf(3),l7(this),this.ph=2,j7(18),m7(this)):xya(this,this.Zu-a)};g.h=Aya.prototype;g.h.zr=null;g.h.re=null;g.h.Xo=!1;g.h.Wx=null;g.h.Dn=null;g.h.Ar=null;g.h.Br=null;g.h.Ne=null;g.h.Eg=-1;g.h.Wk=null;g.h.wk=null;g.h.connect=function(a){this.Br=a;a=r7(this.g,null,this.Br);j7(3);this.Wx=(0,g.H)();var b=this.g.G;null!=b?(this.Wk=b[0],(this.wk=b[1])?(this.Ne=1,Bya(this)):(this.Ne=2,t7(this))):(J6(a,"MODE","init"),this.re=new f7(this,void 0,void 0,void 0),this.re.li=this.zr,g7(this.re,a,!1,null,!0),this.Ne=0)};
g.h.YG=function(a){if(a)this.Ne=2,t7(this);else{j7(4);var b=this.g;b.jf=b.eh.Eg;A7(b,9)}a&&this.uf(2)};
g.h.Tq=function(a){return this.g.Tq(a)};
g.h.abort=function(){this.re&&(this.re.cancel(),this.re=null);this.Eg=-1};
g.h.Vx=function(){return!1};
g.h.CB=function(a,b){this.Eg=a.Xk;if(0==this.Ne)if(b){try{var c=this.o.parse(b)}catch(d){c=this.g;c.jf=this.Eg;A7(c,2);return}this.Wk=c[0];this.wk=c[1]}else c=this.g,c.jf=this.Eg,A7(c,2);else if(2==this.Ne)if(this.Xo)j7(7),this.Ar=(0,g.H)();else if("11111"==b){if(j7(6),this.Xo=!0,this.Dn=(0,g.H)(),c=this.Dn-this.Wx,!g.sd||g.qc(10)||500>c)this.Eg=200,this.re.cancel(),j7(12),s7(this.g,this,!0)}else j7(8),this.Dn=this.Ar=(0,g.H)(),this.Xo=!1};
g.h.Lo=function(){this.Eg=this.re.Xk;if(this.re.yf)0==this.Ne?this.wk?(this.Ne=1,Bya(this)):(this.Ne=2,t7(this)):2==this.Ne&&((!g.sd||g.qc(10)?!this.Xo:200>this.Ar-this.Dn)?(j7(11),s7(this.g,this,!1)):(j7(12),s7(this.g,this,!0)));else{0==this.Ne?j7(9):2==this.Ne&&j7(10);var a=this.g;a.jf=this.Eg;A7(a,2)}};
g.h.Pl=function(){return this.g.Pl()};
g.h.isActive=function(){return this.g.isActive()};
g.h.uf=function(a){this.g.uf(a)};g.h=u7.prototype;g.h.Jk=null;g.h.Qd=null;g.h.uc=null;g.h.yr=null;g.h.Gn=null;g.h.mw=null;g.h.Vn=null;g.h.El=0;g.h.RN=0;g.h.sd=null;g.h.gh=null;g.h.xg=null;g.h.Zh=null;g.h.eh=null;g.h.Cp=null;g.h.Ej=-1;g.h.Vy=-1;g.h.jf=-1;g.h.jj=0;g.h.aj=0;g.h.Xh=8;var B7=new g.zf;g.A(Dya,g.Ye);g.A(Eya,g.Ye);g.A(Fya,g.Ye);g.h=u7.prototype;g.h.connect=function(a,b,c,d,e){j7(0);this.yr=b;this.Jk=c||{};d&&g.t(e)&&(this.Jk.OSID=d,this.Jk.OAID=e);this.D?(o7((0,g.z)(this.Mw,this,a),100),Jya(this)):this.Mw(a)};
g.h.Mw=function(a){this.eh=new Aya(this);this.eh.zr=null;this.eh.o=this.C;this.eh.connect(a)};
g.h.Vx=function(){return 0==this.g};
g.h.HB=function(a){this.gh=null;Mya(this,a)};
g.h.GB=function(){this.xg=null;this.uc=new f7(this,this.A,"rpc",this.F);this.uc.li=null;this.uc.Cr=0;var a=this.mw.clone();g.sm(a,"RID","rpc");g.sm(a,"SID",this.A);g.sm(a,"CI",this.Cp?"0":"1");g.sm(a,"AID",this.Ej);v7(this,a);if(!g.sd||g.qc(10))g.sm(a,"TYPE","xmlhttp"),g7(this.uc,a,!0,this.Vn,!1);else{g.sm(a,"TYPE","html");var b=this.uc,c=!!this.Vn;b.rj=3;b.oh=I6(a.clone());wya(b,c)}};
g.h.CB=function(a,b){if(0!=this.g&&(this.uc==a||this.Qd==a))if(this.jf=a.Xk,this.Qd==a&&3==this.g)if(7<this.Xh){try{var c=this.C.parse(b)}catch(f){c=null}if(g.xa(c)&&3==c.length)if(0==c[0])a:{if(!this.xg){if(this.uc)if(this.uc.Wj+3E3<this.Qd.Wj)x7(this),this.uc.cancel(),this.uc=null;else break a;z7(this);j7(19)}}else this.Vy=c[1],0<this.Vy-this.Ej&&37500>c[2]&&this.Cp&&0==this.aj&&!this.Zh&&(this.Zh=o7((0,g.z)(this.tO,this),6E3));else A7(this,11)}else b!=gAa.bX.g&&A7(this,11);else if(this.uc==a&&
x7(this),!g.E(b)){c=this.C.parse(b);g.xa(c);for(var d=0;d<c.length;d++){var e=c[d];this.Ej=e[0];e=e[1];2==this.g?"c"==e[0]?(this.A=e[1],this.Vn=e[2],e=e[3],null!=e?this.Xh=e:this.Xh=6,this.g=3,this.sd&&this.sd.Bw(),this.mw=r7(this,this.Pl()?this.Vn:null,this.yr),Nya(this)):"stop"==e[0]&&A7(this,7):3==this.g&&("stop"==e[0]?A7(this,7):"noop"!=e[0]&&this.sd&&this.sd.Aw(e),this.aj=0)}}};
g.h.tO=function(){null!=this.Zh&&(this.Zh=null,this.uc.cancel(),this.uc=null,z7(this),j7(20))};
g.h.Lo=function(a){if(this.uc==a){x7(this);this.uc=null;var b=2}else if(this.Qd==a)this.Qd=null,b=1;else return;this.jf=a.Xk;if(0!=this.g)if(a.yf)1==b?(b=(0,g.H)()-a.Wj,B7.dispatchEvent(new Eya(B7,a.Li?a.Li.length:0,b,this.jj)),w7(this),this.B.length=0):Nya(this);else{var c=a.ph,d;if(!(d=3==c||7==c||0==c&&0<this.jf)){if(d=1==b)this.Qd||this.gh||1==this.g||2<=this.jj?d=!1:(this.gh=o7((0,g.z)(this.HB,this,a),Oya(this,this.jj)),this.jj++,d=!0);d=!(d||2==b&&z7(this))}if(d)switch(c){case 1:A7(this,5);
break;case 4:A7(this,10);break;case 3:A7(this,6);break;case 7:A7(this,12);break;default:A7(this,2)}}};
g.h.wH=function(a){if(!g.D(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.FT=function(a){a?j7(2):(j7(1),Pya(this,8))};
g.h.Tq=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.$w;a.G=!1;return a};
g.h.isActive=function(){return!!this.sd&&this.sd.isActive(this)};
g.h.uf=function(a){B7.dispatchEvent(new Fya(B7,a))};
g.h.Pl=function(){return!(!g.sd||g.qc(10))};
g.h=Qya.prototype;g.h.Bw=function(){};
g.h.Aw=function(){};
g.h.zw=function(){};
g.h.Iq=function(){};
g.h.Cx=function(){return{}};
g.h.isActive=function(){return!0};g.A(D7,g.M);D7.prototype.A=function(){500<this.xc&&24E4>2*this.xc&&(this.xc*=2);this.B();this.o&&this.start()};
D7.prototype.start=function(){g.Ot(this.g,this.xc);this.o=(0,g.H)()+this.xc};
D7.prototype.stop=function(){this.g.stop();this.o=0};
D7.prototype.isActive=function(){return this.g.isActive()};g.A(E7,Qya);g.h=E7.prototype;g.h.subscribe=function(a,b,c){return this.A.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.A.unsubscribe(a,b,c)};
g.h.Kd=function(a){return this.A.Kd(a)};
g.h.U=function(a,b){return this.A.U.apply(this.A,arguments)};
g.h.dispose=function(){this.J||(this.J=!0,g.We(this.A),Tya(this),g.We(this.o),this.o=null)};
g.h.ia=function(){return this.J};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.I="";this.o.stop();this.C=a||null;this.B=b||0;a=this.L+"/test";b=this.L+"/bind";var d=new u7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.N),e=this.g;e&&(e.sd=null);d.sd=this;this.g=d;e?this.g.connect(a,b,this.D,e.A,e.Ej):c?this.g.connect(a,b,this.D,c.sessionId,c.arrayId):this.g.connect(a,b,this.D)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.cc(c,b);this.o.isActive()||2==(this.g?this.g.g:0)?this.F.push(c):F7(this)&&Kya(this.g,c)};
g.h.Bw=function(){C7(this.o);this.C=null;this.B=0;if(this.F.length){var a=this.F;this.F=[];for(var b=0,c=a.length;b<c;++b)Kya(this.g,a[b])}this.U("handlerOpened")};
g.h.zw=function(a){var b=2==a&&401==this.g.jf;if(4!=a&&!b){if(6==a||410==this.g.jf)b=this.o,b.g.stop(),b.xc=500;this.o.start()}this.U("handlerError",a)};
g.h.Iq=function(a){if(!this.o.isActive())this.U("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.F.push(d)}};
g.h.Cx=function(){var a={v:2};this.I&&(a.gsessionid=this.I);0!=this.B&&(a.ui=""+this.B);0!=this.G&&(a.ui=""+this.G);this.C&&g.cc(a,this.C);return a};
g.h.Aw=function(a){"S"==a[0]?this.I=a[1]:"gracefulReconnect"==a[0]?(C7(this.o),this.o.start(),Iya(this.g)):this.U("handlerMessage",new Rya(a[0],a[1]))};
g.h.mU=function(){this.o.isActive();var a=this.g,b=0;a.uc&&b++;a.Qd&&b++;0!=b?this.o.start():this.connect(this.C,this.B)};G7.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
G7.prototype.A=function(a,b){a(Error("Request error: "+b.status))};
G7.prototype.C=function(a){a(Error("request timed out"))};var aza=(0,g.H)(),J7=null,M7=Array(50),L7=-1,N7=!1;g.A(O7,g.lF);O7.prototype.ie=function(){return this.g};
O7.prototype.contains=function(a){return!!Q6(this.g,a)};
O7.prototype.get=function(a){return a?R6(this.g,a):null};
O7.prototype.info=function(a){K7(this.F,a)};g.A(P7,g.lF);var iAa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=P7.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.Ba)&&this.DD()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.Ba)||(g.FD(this.Ba),this.Ba=window.NaN)};
g.h.W=function(){this.stop();P7.Y.W.call(this)};
g.h.DD=function(){this.Ba=window.NaN;this.g=g.TD(H7(this.D,"/pairing/get_screen"),{method:"POST",Pb:{pairing_code:this.C},timeout:5E3,Lb:(0,g.z)(this.oU,this),onError:(0,g.z)(this.nU,this),wd:(0,g.z)(this.pU,this)})};
g.h.oU=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.A;c.name=this.B;this.U("pairingComplete",new L6(c))};
g.h.nU=function(a){this.g=null;a.status&&404==a.status?this.o>=iAa.length?this.U("pairingFailed",Error("DIAL polling timed out")):(a=iAa[this.o],this.Ba=g.DD((0,g.z)(this.DD,this),a),this.o++):this.U("pairingFailed",Error("Server error "+a.status))};
g.h.pU=function(){this.g=null;this.U("pairingFailed",Error("Server not responding"))};g.A(R7,O7);g.h=R7.prototype;g.h.start=function(){Q7(this)&&this.U("screenChange");!g.lG("yt-remote-lounge-token-expiration")&&eza(this);g.FD(this.o);this.o=g.DD((0,g.z)(this.start,this),1E4)};
g.h.add=function(a,b){Q7(this);bza(this,a);S7(this,!1);this.U("screenChange");b(a);a.token||eza(this)};
g.h.remove=function(a,b){var c=Q7(this);dza(this,a)&&(S7(this,!1),c=!0);b(a);c&&this.U("screenChange")};
g.h.yp=function(a,b,c,d){var e=Q7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,S7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.U("screenChange")};
g.h.W=function(){g.FD(this.o);R7.Y.W.call(this)};
g.h.bI=function(a){Q7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}S7(this,!b);b&&K7(this.F,"Missed "+b+" lounge tokens.")};
g.h.aI=function(a){K7(this.F,"Requesting lounge tokens failed: "+a)};g.A(U7,g.lF);g.h=U7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.lG("yt-remote-fast-check-period")||"0",10);(this.B=(0,g.H)()-144E5<a?0:a)?W7(this):(this.B=(0,g.H)()+3E5,g.kG("yt-remote-fast-check-period",this.B),this.ju())};
g.h.isEmpty=function(){return g.Vb(this.g)};
g.h.update=function(){T7("Updating availability on schedule.");var a=this.D(),b=g.Kb(this.g,function(b,d){return b&&!!R6(a,d)},this);
V7(this,b)};
g.h.W=function(){g.FD(this.A);this.A=window.NaN;this.o&&(this.o.abort(),this.o=null);U7.Y.W.call(this)};
g.h.ju=function(){g.FD(this.A);this.A=window.NaN;this.o&&this.o.abort();var a=hza(this);if(g.Nb(a)){var b=H7(this.C,"/pairing/get_screen_availability");this.o=I7(this.C,b,{lounge_token:g.Pb(a).join(",")},(0,g.z)(this.pR,this,a),(0,g.z)(this.oR,this))}else V7(this,{}),W7(this)};
g.h.pR=function(a,b){this.o=null;var c=g.Pb(hza(this));if(g.fb(c,g.Pb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;V7(this,d);W7(this)}else this.dc("Changing Screen set during request."),this.ju()};
g.h.oR=function(a){this.dc("Screen availability failed: "+a);this.o=null;W7(this)};
g.h.dc=function(a){K7("OnlineScreenService",a)};g.A(X7,O7);g.h=X7.prototype;g.h.start=function(){this.A.start();this.o.start();this.g.length&&(this.U("screenChange"),this.o.isEmpty()||this.U("onlineScreenChange"))};
g.h.add=function(a,b,c){this.A.add(a,b,c)};
g.h.remove=function(a,b,c){this.A.remove(a,b,c);this.o.update()};
g.h.yp=function(a,b,c,d){this.A.contains(a)?this.A.yp(a,b,c,d):(a="Updating name of unknown screen: "+a.name,K7(this.F,a),d(Error(a)))};
g.h.ie=function(a){return a?this.g:g.Ua(this.g,(0,g.Gd)(this.B,function(a){return!this.contains(a)},this))};
g.h.ED=function(){return(0,g.Gd)(this.ie(!0),function(a){return!!this.o.g[a.id]},this)};
g.h.FD=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new P7(this.D,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(a){g.We(f);d(Y7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.We(f);e(a)});
f.start();return(0,g.z)(f.stop,f)};
g.h.rU=function(a,b,c,d){g.TD(H7(this.D,"/pairing/get_screen"),{method:"POST",Pb:{pairing_code:a},timeout:5E3,Lb:(0,g.z)(function(a,d){var e=new L6(d.screen||{});if(!e.name||lza(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);lza(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(Y7(this,e))},this),
onError:(0,g.z)(function(a){d(Error("pairing request failed: "+a.status))},this),
wd:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.h.W=function(){g.We(this.A);g.We(this.o);X7.Y.W.call(this)};
g.h.nI=function(){mza(this);this.U("screenChange");this.o.update()};
X7.prototype.dispose=X7.prototype.dispose;g.A($7,g.lF);g.h=$7.prototype;g.h.Mo=function(a){this.A=a;this.U("sessionScreen",this.A)};
g.h.pe=function(a){this.ia()||(a&&a8(this,""+a),this.A=null,this.U("sessionScreen",null))};
g.h.info=function(a){K7(this.N,a)};
g.h.HD=function(){return null};
g.h.qu=function(a){var b=this.o;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){a8(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.W=function(){this.qu("");$7.Y.W.call(this)};g.A(b8,$7);g.h=b8.prototype;g.h.pu=function(a){if(this.g){if(this.g==a)return;a8(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.D);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.C)}this.g=a;this.g.addUpdateListener(this.D);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.C);oza(this)};
g.h.Fj=function(a){this.info("launchWithParams no-op for Cast: "+g.ug(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.z)(function(){this.pe()},this),(0,g.z)(function(){this.pe(Error("Failed to stop receiver app."))},this)):this.pe(Error("Stopping cast device witout session."))};
g.h.qu=g.y;g.h.W=function(){this.info("disposeInternal");g.FD(this.B);this.B=0;this.g&&(this.g.removeUpdateListener(this.D),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.C));this.g=null;b8.Y.W.call(this)};
g.h.qS=function(a,b){if(!this.ia())if(b){var c=g.Uw(b);if(c){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.ug(c));switch(d){case "mdxSessionStatus":nza(this,c.screenId);break;default:a8(this,"Unknown youtube message: "+d)}}else a8(this,"Unable to parse message.")}else a8(this,"No data in message.")};
g.h.Ox=function(a,b,c,d){kza(this.I,this.o.label,a,this.o.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(a8(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.DD((0,g.z)(this.Ox,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.HD=function(){return this.g};
g.h.sU=function(a){this.ia()||a||(a8(this,"Cast session died."),this.pe())};g.A(c8,$7);g.h=c8.prototype;g.h.pu=function(a){this.B=a;this.B.addUpdateListener(this.L)};
g.h.Fj=function(a){this.C=a;this.F()};
g.h.stop=function(){this.g();this.g=g.y;g.FD(this.D);this.B?this.B.stop((0,g.z)(this.pe,this,null),(0,g.z)(this.pe,this,"Failed to stop DIAL device.")):this.pe()};
g.h.W=function(){this.g();this.g=g.y;g.FD(this.D);this.B&&this.B.removeUpdateListener(this.L);this.B=null;c8.Y.W.call(this)};
g.h.vU=function(a){this.ia()||a||(a8(this,"DIAL session died."),this.g(),this.g=g.y,this.pe())};
g.h.qs=function(a){this.J=P6();if(this.C){var b=new window.chrome.cast.DialLaunchResponse(!0,qza(this));a(b);pza(this)}else this.F=(0,g.z)(function(){g.FD(this.D);this.F=g.y;this.D=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,qza(this));a(b);pza(this)},this),this.D=g.DD((0,g.z)(function(){this.F()},this),100)};
g.h.DJ=function(a,b,c){kza(this.I,this.G.receiver.label,a,this.o.friendlyName,(0,g.z)(function(a){a&&a.token?(this.Mo(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.qs(b,c)},this),(0,g.z)(function(a){a8(this,"Failed to get DIAL screen: "+a);
this.qs(b,c)},this))};g.A(d8,$7);d8.prototype.stop=function(){this.pe()};
d8.prototype.pu=g.y;d8.prototype.Fj=function(){g.FD(this.g);this.g=window.NaN;var a=R6(this.I.ie(),this.o.label);a?this.Mo(a):this.pe(Error("No such screen"))};
d8.prototype.W=function(){g.FD(this.g);this.g=window.NaN;d8.Y.W.call(this)};g.A(e8,g.lF);g.h=e8.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.F);this.G||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.z)(this.DB,this),(0,g.z)(this.aR,this),d,e);c.customDialLaunchCallback=(0,g.z)(this.eP,this);window.chrome.cast.initialize(c,
(0,g.z)(function(){this.ia()||(window.chrome.cast.addReceiverActionListener(this.B),Yya(),this.o.subscribe("onlineScreenChange",(0,g.z)(this.GD,this)),this.A=sza(this),window.chrome.cast.setCustomReceivers(this.A,g.y,(0,g.z)(function(a){this.dc("Failed to set initial custom receivers: "+g.ug(a))},this)),this.U("yt-remote-cast2-availability-change",g8(this)),b(!0))},this),(0,g.z)(function(a){this.dc("Failed to initialize API: "+g.ug(a));
b(!1)},this))};
g.h.nT=function(a,b){f8("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.A;if(!a||c&&c.id!=a)f8("Unsetting old screen status: "+this.g.o.friendlyName),h8(this,null)}if(a&&b){if(!this.g){c=R6(this.o.ie(),a);if(!c){f8("setConnectedScreenStatus: Unknown screen.");return}var d=rza(this,c);d||(f8("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.A.push(d),
window.chrome.cast.setCustomReceivers(this.A,g.y,(0,g.z)(function(a){this.dc("Failed to set initial custom receivers: "+g.ug(a))},this)));
f8("setConnectedScreenStatus: new active receiver: "+d.friendlyName);h8(this,new d8(this.o,d),!0)}this.g.qu(b)}else f8("setConnectedScreenStatus: no screen.")};
g.h.oT=function(a){this.ia()?this.dc("Setting connection data on disposed cast v2"):this.g?this.g.Fj(a):this.dc("Setting connection data without a session")};
g.h.uU=function(){this.ia()?this.dc("Stopping session on disposed cast v2"):this.g?(this.g.stop(),h8(this,null)):f8("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.z)(this.DB,this),(0,g.z)(this.tR,this))};
g.h.W=function(){this.o.unsubscribe("onlineScreenChange",(0,g.z)(this.GD,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.B);g.Sa(g.x("yt.mdx.remote.debug.handlers_")||[],Vya);g.We(this.g);e8.Y.W.call(this)};
g.h.dc=function(a){K7("Controller",a)};
g.h.EB=function(a,b){this.g==a&&(b||h8(this,null),this.U("yt-remote-cast2-session-change",b))};
g.h.WQ=function(a,b){if(!this.ia())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),f8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.o.label!=a.label)f8("onReceiverAction_: Stopping active receiver: "+this.g.o.friendlyName),this.g.stop();else{f8("onReceiverAction_: Casting to active receiver.");this.g.A&&this.U("yt-remote-cast2-session-change",this.g.A);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:h8(this,
new d8(this.o,a));break;case window.chrome.cast.ReceiverType.DIAL:h8(this,new c8(this.o,a,this.D));break;case window.chrome.cast.ReceiverType.CAST:h8(this,new b8(this.o,a));break;default:this.dc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.o.label==a.label?this.g.stop():this.dc("Stopping receiver w/o session: "+a.friendlyName)}else this.dc("onReceiverAction_ called without receiver.")};
g.h.eP=function(a){if(this.ia())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.dc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.o:null;if(!c||c.label!=b.label)return this.dc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.A)return f8("Reselecting dial screen."),
this.U("yt-remote-cast2-session-change",this.g.A),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.dc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);h8(this,new c8(this.o,b,this.D))}b=this.g;b.G=a;return b.G.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.z)(b.DJ,b,(b.G.extraData||{}).screenId||null)):new window.Promise((0,g.z)(b.qs,b))};
g.h.DB=function(a){if(!this.ia()){f8("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)f8("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),h8(this,new b8(this.o,b),!0);else{this.dc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.o,d=R6(this.o.ie(),c.label);
d&&M6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(f8("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.We(this.g),this.g=new b8(this.o,b),this.g.subscribe("sessionScreen",(0,g.z)(this.EB,this,this.g)),this.g.Fj(null));this.g.pu(a)}}};
g.h.tU=function(){return this.g?this.g.HD():null};
g.h.tR=function(a){this.ia()||(this.dc("Failed to estabilish a session: "+g.ug(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&h8(this,null))};
g.h.aR=function(a){f8("Receiver availability updated: "+a);if(!this.ia()){var b=g8(this);this.C=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;g8(this)!=b&&this.U("yt-remote-cast2-availability-change",g8(this))}};
g.h.GD=function(){this.ia()||(this.A=sza(this),f8("Updating custom receivers: "+g.ug(this.A)),window.chrome.cast.setCustomReceivers(this.A,g.y,(0,g.z)(function(){this.dc("Failed to set custom receivers.")},this)),this.U("yt-remote-cast2-availability-change",g8(this)))};
e8.prototype.setLaunchParams=e8.prototype.oT;e8.prototype.setConnectedScreenStatus=e8.prototype.nT;e8.prototype.stopSession=e8.prototype.uU;e8.prototype.getCastSession=e8.prototype.tU;e8.prototype.requestSession=e8.prototype.requestSession;e8.prototype.init=e8.prototype.init;e8.prototype.dispose=e8.prototype.dispose;var n8=[];s8.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";t8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.Of=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.C=a.seekableStart,this.A=a.seekableEnd,this.I=a.duration,this.J=a.loadedTime,this.B=a.liveIngestionTime,this.D=!(0,window.isNaN)(this.B))};
s8.prototype.ob=function(){return 1==this.g};
s8.prototype.getDuration=function(){return this.D?this.I+u8(this):this.I};
s8.prototype.clone=function(){return new s8(y8(this))};g.A(A8,g.lF);g.h=A8.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.y,G8(this,"play")):F8(this,"play"),E8(this,1,w8(B8(this))),this.U("remotePlayerChange")):C8(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.y,G8(this,"pause")):F8(this,"pause"),E8(this,2,w8(B8(this))),this.U("remotePlayerChange")):C8(this,this.pause)};
g.h.CD=function(a){if(1==this.g){if(this.o){var b=B8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.ob()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.y,G8(this,"seekTo",{newTime:a}))}else F8(this,"seekTo",{newTime:a});E8(this,3,a);this.U("remotePlayerChange")}else C8(this,g.Da(this.CD,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.y,G8(this,"stopVideo")):F8(this,"stopVideo");var a=B8(this);a.index=-1;a.videoId="";t8(a);D8(this,a);this.U("remotePlayerChange")}else C8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=B8(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.z)(function(){K7("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.dc("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.z)(function(){K7("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.dc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);F8(this,"setVolume",e)}c.muted=b;c.volume=a;D8(this,c)}else C8(this,g.Da(this.setVolume,a,b))};
g.h.JC=function(a,b){if(1==this.g){var c=B8(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.ug(b.style),g.cc(d,c.o));F8(this,"setSubtitlesTrack",d);D8(this,c)}else C8(this,g.Da(this.JC,a,b))};
g.h.ev=function(a,b){if(1==this.g){F8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Uc.id});var c=B8(this);c.audioTrackId=b.Uc.id;D8(this,c)}else C8(this,g.Da(this.ev,a,b))};
g.h.BD=function(a,b){if(1==this.g){if(a&&b){var c=B8(this);x8(c,a,b);D8(this,c)}F8(this,"previous")}else C8(this,g.Da(this.BD,a,b))};
g.h.AD=function(a,b){if(1==this.g){if(a&&b){var c=B8(this);x8(c,a,b);D8(this,c)}F8(this,"next")}else C8(this,g.Da(this.AD,a,b))};
g.h.bx=function(){1==this.g?F8(this,"dismissAutoplay"):C8(this,this.bx)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.U("proxyStateChange",a,this.g)}A8.Y.dispose.call(this)};
g.h.W=function(){Eza(this);this.B=null;this.C.clear();z8(this,null);A8.Y.W.call(this)};
g.h.fv=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.U("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)g.bC(this.C).apply(this);else 3==a&&this.dispose()}};
g.h.SQ=function(a,b){this.U(a,b)};
g.h.AO=function(a){if(!a)this.Gl(null),z8(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=B8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)K7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,D8(this,b)}};
g.h.Gl=function(a){K7("CP","Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.G);if(this.o=a)this.o.addUpdateListener(this.G),Fza(this),this.U("remotePlayerChange")};
g.h.zO=function(a){a?(Fza(this),this.U("remotePlayerChange")):this.Gl(null)};
g.h.NO=function(){var a=Bza();a&&z8(this,a)};
g.h.dc=function(a){K7("CP",a)};g.A(H8,g.lF);g.h=H8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime;g.t(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.t(k)&&(l.currentIndex=k);c&&(this.fb.listId=c);this.fb.videoId=d;this.fb.index=k||0;this.fb.state=3;v8(this.fb,m);this.B="UNSUPPORTED";I8("Connecting with setPlaylist and params: "+g.ug(l));this.g.connect({method:"setPlaylist",params:g.ug(l)},a,$xa())}else I8("Connecting without params"),
this.g.connect({},a,$xa());Hza(this)};
g.h.dispose=function(){this.ia()||(this.U("beforeDispose"),J8(this,3));H8.Y.dispose.call(this)};
g.h.W=function(){K8(this);M8(this);L8(this);g.FD(this.I);this.I=window.NaN;g.FD(this.J);this.J=window.NaN;this.A=null;g.XE(this.R);this.R.length=0;this.g.dispose();H8.Y.W.call(this);this.B=this.F=this.o=this.fb=this.g=null};
g.h.SH=function(){this.D(2)};
g.h.EO=function(){I8("Channel opened");this.O&&(this.O=!1,L8(this),this.N=g.DD((0,g.z)(function(){I8("Timing out waiting for a screen.");this.D(1)},this),15E3));
dya(Sya(this.g),this.aa)};
g.h.BO=function(){I8("Channel closed");(0,window.isNaN)(this.C)?W6(!0):W6();this.dispose()};
g.h.CO=function(a){W6();(0,window.isNaN)(this.G())?(I8("Channel error: "+a+" without reconnection"),this.dispose()):(this.O=!0,I8("Channel error: "+a+" with reconnection in "+this.G()+" ms"),J8(this,2))};
g.h.DO=function(a){a.params?I8("Received: action="+a.action+", params="+g.ug(a.params)):I8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Uw(a.params.devices);this.o=(0,g.J)(a,function(a){return new K6(a)});
a=!!g.Ia(this.o,function(a){return"LOUNGE_SCREEN"==a.type});
Kza(this,a);break;case "loungeScreenDisconnected":g.Ta(this.o,function(a){return"LOUNGE_SCREEN"==a.type});
Kza(this,!1);break;case "remoteConnected":var b=new K6(g.Uw(a.params.device));g.Ia(this.o,function(a){return b?a.id==b.id:!1})||g.Qa(this.o,b);
break;case "remoteDisconnected":b=new K6(g.Uw(a.params.device));g.Ta(this.o,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":Mza(this,a);break;case "nowPlaying":Oza(this,a);break;case "onStateChange":Nza(this,a);break;case "onAdStateChange":Pza(this,a);break;case "onVolumeChanged":Qza(this,a);break;case "onSubtitlesTrackChanged":Lza(this,a);break;case "nowAutoplaying":Rza(this,a);break;case "autoplayDismissed":this.U("autoplayDismissed");break;case "autoplayUpNext":this.F=a.params.videoId||null;this.U("autoplayUpNext",this.F);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.U("autoplayModeChange",this.B);"DISABLED"==this.B&&this.U("autoplayDismissed");break;case "onHasPreviousNextChanged":Sza(this,a);break;case "requestAssistedSignIn":this.U("assistedSignInRequested",a.params.authCode);break;default:I8("Unrecognized action: "+a.action)}};
g.h.ZS=function(){if(this.A){var a=this.A;this.A=null;this.fb.videoId!=a&&N8(this,"getNowPlaying")}};
H8.prototype.subscribe=H8.prototype.subscribe;H8.prototype.unsubscribeByKey=H8.prototype.Kd;H8.prototype.ea=function(){var a=3;this.ia()||(a=0,(0,window.isNaN)(this.G())?F7(this.g)&&(0,window.isNaN)(this.C)&&(a=1):a=2);return a};
H8.prototype.getProxyState=H8.prototype.ea;H8.prototype.D=function(a){I8("Disconnecting with "+a);K8(this);this.U("beforeDisconnect",a);1==a&&W6();Tya(this.g,a);this.dispose()};
H8.prototype.disconnect=H8.prototype.D;H8.prototype.da=function(){var a=this.fb;this.A&&(a=this.fb.clone(),x8(a,this.A,a.index));return y8(a)};
H8.prototype.getPlayerContextData=H8.prototype.da;
H8.prototype.la=function(a){var b=new s8(a);b.videoId&&b.videoId!=this.fb.videoId&&(this.A=b.videoId,g.FD(this.I),this.I=g.DD((0,g.z)(this.ZS,this),5E3));var c=[];this.fb.listId==b.listId&&this.fb.videoId==b.videoId&&this.fb.index==b.index||c.push("remoteQueueChange");this.fb.g==b.g&&this.fb.volume==b.volume&&this.fb.muted==b.muted&&w8(this.fb)==w8(b)&&g.ug(this.fb.o)==g.ug(b.o)||c.push("remotePlayerChange");this.fb.reset(a);(0,g.C)(c,function(a){this.U(a)},this)};
H8.prototype.setPlayerContextData=H8.prototype.la;H8.prototype.X=function(){var a=this.g.D.id,b=g.Ia(this.o,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
H8.prototype.getOtherConnectedRemoteId=H8.prototype.X;H8.prototype.G=function(){var a=this.g;return a.o.isActive()?a.o.o-(0,g.H)():window.NaN};
H8.prototype.getReconnectTimeout=H8.prototype.G;H8.prototype.Z=function(){return this.B||"UNSUPPORTED"};
H8.prototype.getAutoplayMode=H8.prototype.Z;H8.prototype.ca=function(){return this.F||""};
H8.prototype.getAutoplayVideoId=H8.prototype.ca;H8.prototype.pa=function(){if(!(0,window.isNaN)(this.G())){var a=this.g.o;g.Pt(a.g);a.start()}};
H8.prototype.reconnect=H8.prototype.pa;H8.prototype.ga=function(a,b){N8(this,a,b);Jza(this)};
H8.prototype.sendMessage=H8.prototype.ga;g.A(O8,O7);g.h=O8.prototype;g.h.ie=function(a){return this.gd.$_gs(a)};
g.h.contains=function(a){return!!this.gd.$_c(a)};
g.h.get=function(a){return this.gd.$_g(a)};
g.h.start=function(){this.gd.$_st()};
g.h.add=function(a,b,c){this.gd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.gd.$_r(a,b,c)};
g.h.yp=function(a,b,c,d){this.gd.$_un(a,b,c,d)};
g.h.W=function(){for(var a=0,b=this.o.length;a<b;++a)this.gd.$_ubk(this.o[a]);this.o.length=0;this.gd=null;O8.Y.W.call(this)};
g.h.qU=function(){this.U("screenChange")};
g.h.yQ=function(){this.U("onlineScreenChange")};
X7.prototype.$_st=X7.prototype.start;X7.prototype.$_gspc=X7.prototype.rU;X7.prototype.$_gsppc=X7.prototype.FD;X7.prototype.$_c=X7.prototype.contains;X7.prototype.$_g=X7.prototype.get;X7.prototype.$_a=X7.prototype.add;X7.prototype.$_un=X7.prototype.yp;X7.prototype.$_r=X7.prototype.remove;X7.prototype.$_gs=X7.prototype.ie;X7.prototype.$_gos=X7.prototype.ED;X7.prototype.$_s=X7.prototype.subscribe;X7.prototype.$_ubk=X7.prototype.Kd;var P8=null,Q8=null,e9=null,U8=[];g.p(f9,g.M);g.h=f9.prototype;
g.h.W=function(){g.M.prototype.W.call(this);this.B.stop();this.C.stop();this.L.stop();this.O();this.g.unsubscribe("proxyStateChange",this.BB,this);this.g.unsubscribe("remotePlayerChange",this.Il,this);this.g.unsubscribe("remoteQueueChange",this.No,this);this.g.unsubscribe("autoplayUpNext",this.aB,this);this.g.unsubscribe("previousNextChange",this.yB,this);this.g.unsubscribe("nowAutoplaying",this.qB,this);this.g.unsubscribe("autoplayDismissed",this.ZA,this);this.g=this.G=null};
g.h.Kz=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(i9(this)){if(1081!=B8(this.g).g||"control_seek"!=a)switch(a){case "control_toggle_play_pause":B8(this.g).ob()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.J.pj(c[0],c[1]);break;case "control_subtitles_set_track":j9(this,c[0]);break;case "control_set_audio_track":c=c[0],i9(this)&&this.g.ev(this.o.fa(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.o.getCurrentTime();k9(this,0==c?void 0:c);break;case "control_seek":k9(this,c[0]);break;case "control_subtitles_set_track":j9(this,c[0]);break;case "control_set_audio_track":c=c[0],i9(this)&&this.g.ev(this.o.fa(1).videoId,c)}};
g.h.yO=function(a){this.L.OH(a)};
g.h.QT=function(a){this.Kz("control_subtitles_set_track",g.Vb(a)?null:a)};
g.h.VC=function(){var a=this.o.Bc("captions","track");g.Vb(a)||j9(this,a)};
g.h.oB=function(a){if(i9(this)){this.g.unsubscribe("remotePlayerChange",this.Il,this);var b=Math.round(a.volume);a=!!a.muted;var c=B8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.N.start();this.g.subscribe("remotePlayerChange",this.Il,this)}};
g.h.RP=function(){g.Vb(this.D)||dAa(this,this.D);this.F=!1};
g.h.BB=function(a,b){this.C.stop();2==b&&this.SC()};
g.h.Il=function(){if(i9(this)){this.B.stop();var a=B8(this.g);switch(a.g){case 1081:case 1:h9(this,new g.eO(8));this.RC();break;case 1085:case 3:h9(this,new g.eO(9));break;case 1083:case 0:h9(this,new g.eO(2));this.J.stop();g9(this,this.o.fa().lengthSeconds);break;case 1084:h9(this,new g.eO(4));break;case 2:h9(this,new g.eO(4));g9(this,w8(a));break;case -1:h9(this,new g.eO(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.U("YTP_MDX_PLAYER_ERROR")},h9(this,new g.eO(128,a))}a=B8(this.g).o;
var b=this.D;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.D=a,dAa(this,a));a=B8(this.g);-1==a.volume||Math.round(this.o.getVolume())==a.volume&&this.o.isMuted()==a.muted||this.N.isActive()||this.tD()}else cAa(this)};
g.h.yB=function(){this.o.U("mdxpreviousnextchange")};
g.h.No=function(){i9(this)||cAa(this)};
g.h.XG=function(){this.g.bx()};
g.h.aB=function(a){a&&(a=g.TD("/watch_queue_ajax",{method:"GET",cd:{action_get_watch_queue_item:1,video_id:a},Lb:(0,g.z)(this.SR,this)}))&&(this.O=(0,g.z)(a.abort,a))};
g.h.SR=function(a,b){var c=new g.fN({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.o.U("mdxautoplayupnext",c)};
g.h.qB=function(a){(0,window.isNaN)(a)||this.o.U("mdxnowautoplaying",a)};
g.h.ZA=function(){this.o.U("mdxautoplaycanceled")};
g.h.kL=function(a,b){-1==B8(this.g).g?k9(this,a):b&&this.g.CD(a)};
g.h.tD=function(){if(i9(this)){var a=B8(this.g);this.A.Fa(this.R);a.muted?this.o.mute():this.o.cg();this.o.setVolume(a.volume);this.R=this.A.P(this.o,"onVolumeChange",this.oB)}};
g.h.RC=function(){this.B.stop();if(!this.g.ia()){var a=B8(this.g);a.ob()&&h9(this,new g.eO(8));g9(this,w8(a));this.B.start()}};
g.h.SC=function(){this.C.stop();this.B.stop();var a=this.g.B.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.C.start()};g.p(l9,g.X);l9.prototype.B=function(a){fAa(this,a.state)};g.p(m9,g.K_);m9.prototype.J=function(){var a=this.o.Bc("remote","receivers");a&&1<a.length&&!this.o.Bc("remote","quickCast")?(this.G=g.ib(a,this.C,this),g.L_(this,(0,g.J)(a,this.C)),a=this.o.Bc("remote","currentReceiver"),this.tf(this.C(a)),this.enable(!0)):this.enable(!1)};
m9.prototype.C=function(a){return a.key};
m9.prototype.sf=function(a){return"cast-selector-receiver"==a?g.U("YTP_MDX_CAST_SELECTOR"):this.G[a].name};
m9.prototype.ud=function(a){g.K_.prototype.ud.call(this,a);this.o.Id("remote","currentReceiver",this.G[a]);this.B.Qb()};g.p(n9,g.tU);g.h=n9.prototype;g.h.create=function(){Xza(g.CL(g.W(this.g)));this.D.push(g.xF("yt-remote-before-disconnect",this.uO,this));this.D.push(g.xF("yt-remote-connection-change",this.bR,this));this.D.push(g.xF("yt-remote-receiver-availability-change",this.zB,this));this.D.push(g.xF("yt-remote-auto-connect",this.ZQ,this));this.D.push(g.xF("yt-remote-receiver-resumed",this.YQ,this));this.zB()};
g.h.load=function(){this.g.ut();g.tU.prototype.load.call(this);this.C=new f9(this,this.g,this.o);var a=(a=bAa())?a.currentTime:0;var b=d9()?new A8(Z8(),void 0):null;0==a&&b&&(a=w8(B8(b)));0!=a&&(this.I=a||0,this.g.U("progresssync",a,void 0));eAa(this,this.F,this.F);g.G0(this.g.app,6)};
g.h.unload=function(){this.g.U("mdxautoplaycanceled");this.B=this.A;g.Xe(this.C,this.o);this.o=this.C=null;g.tU.prototype.unload.call(this);g.G0(this.g.app,5)};
g.h.W=function(){g.yF(this.D);g.tU.prototype.W.call(this)};
g.h.rl=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.Kz.apply(this.C,[].concat([a],g.pa(c)))};
g.h.KH=function(){return this.loaded?this.C.suggestion:null};
g.h.Of=function(){return this.o?B8(this.o).Of:!1};
g.h.hasNext=function(){return this.o?B8(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.I};
g.h.KK=function(){var a=B8(this.o),b=this.g.fa();return{allowSeeking:this.g.hd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.D?a.B+u8(a):a.B,isPeggedToLive:1>=(a.D?a.A+u8(a):a.A)-this.getCurrentTime(),loaded:a.J,seekableEnd:a.D?a.A+u8(a):a.A,seekableStart:0<a.C?a.C+u8(a):a.C}};
g.h.LK=function(){this.o&&this.o.AD()};
g.h.MK=function(){this.o&&this.o.BD()};
g.h.uO=function(a){1==a&&(this.J=this.o?B8(this.o):null)};
g.h.bR=function(){var a=d9()?new A8(Z8(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.J=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.We(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.J)&&a.videoId==this.g.fa().videoId&&this.g.Rz(a.videoId,w8(a)));this.g.U("videodatachange","newdata",this.g.fa(),3)};
g.h.zB=function(){this.G=[this.A].concat(Zza());var a=$8()||this.A;o9(this,a);this.g.ua("onMdxReceiversChange")};
g.h.ZQ=function(){var a=$8();o9(this,a)};
g.h.YQ=function(){this.B=$8()};
g.h.JK=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?q8():o9(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&q8(),!0):!1}};
g.h.NK=function(){F8(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.xd=function(){return!1};g.BY.remote=n9;})(_yt_player);
